<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [15]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
  """This function takes two 2-D lists (matrices)
and outputs the matrix product"""
    # write your code
  (r1,c1) = len(A),len(A[0])
  (r2,c2) = len(B),len(B[0])
# Only if the columns of the first matrix and rows of the second matrix are same,then the matrix multiplication is possible
  if c1!=r2:
    return "Not possible"
  else:
    res = [[0 for i in range(c2)] for j in range(r1)]
    for i in range(len(A)):
      for j in range(len(B[0])):
        for k in range(len(B)):
          res[i][j] += A[i][k] * B[k][j]
    
    return res
    
    
A = [[1,3,4],[2,5,7],[5,9,6]]
B = [[1,0,0],[0,1,0],[0,0,1]]
print("A*B =",matrix_mul(A, B))


A*B = [[1, 3, 4], [2, 5, 7], [5, 9, 6]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [2]:
from random import uniform
import functools
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(d):
    # your code here for picking an element from with the probability propotional to its magnitude
    #.
    #.import functools
  d=sorted(d)
  sum_d=functools.reduce(lambda a,b : a+b,d)
  d_dash=[] # Normalised array d
  d_tilda=[] #Cumulative sum
  for i in range(len(d)):
    d_dash.append(d[i]/sum_d)
  for i in range(len(d_dash)):
    sum=0
    for j in range(i+1):
      sum+=d_dash[j]
    d_tilda.append(sum)
  """The difference of any consecutive d_tilda[i]-d_tilda[i-1] is directly proportional
to d_dash[i]"""
  from random import uniform
  #Probablity of choosing a number from array is proportional to magnitude
  for i in range(0,30):  
    r= uniform(0,1) # Choosing a number from random normal disb
    for i in range(len(d_tilda)):
      if r <= d_tilda[i]:
        return d[i]

A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()


13
100
27
79
27
45
45
10
28
100
28
10
45
79
100
45
79
100
5
28
28
79
79
100
79
79
45
45
79
5
10
100
45
100
13
5
13
100
28
10
28
100
100
28
79
100
100
27
79
45
79
45
100
79
100
100
100
27
100
27
79
100
27
100
27
100
100
45
27
100
79
10
45
79
45
100
79
27
100
100
79
79
79
45
28
27
79
79
100
100
100
79
28
45
79
79
100
13
100


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [3]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
  s= re.sub("[^0-9]",'',String) # Regex expression to keep only digits 0-9
  s = re.sub("[0-9]",'#',s) #Regex expression to replace digits 0-9 with '#'

  return(s) # modified string which is after replacing the # with digits

replace_digits('#2a$#b%c%561#  ')

'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [16]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
#Reference: https://stackoverflow.com/questions/2374640/how-do-i-calculate-percentiles-with-python-numpy
import math
students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks =  [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

# The below function calulates the percentile value for a given list based on a given percentage
def percentile(lst,percent):
  pos = math.ceil ((len(lst)*percent)/100)
  return sorted(lst)[int(pos)-1]

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    #Using an dict to map marks and students
    d = {}
    i=0
    for mark in marks:
      d[mark]=students[i]
      i=i+1
    #Sorting in descending order and fetching the corresponding students from dict
    marks.sort(reverse=True)
    top_5_students =[] 
    for i in range(5):
      top_5_students.append(d[marks[i]])
    
    #code for computing least 5 students
    least_5_students = []
     #Sorting in ascending order and fetching the corresponding students from dict
    marks.sort()
    for i in range(5):
      least_5_students.append(d[marks[i]])
    
    # write code for computing top least 5 students
    #Calculating 25th and 75th percentile
    students_within_25_and_75 = []
    low = percentile(marks,25)
    high = percentile(marks,75)
    count=0
    for ele in marks:
      if ele >= low and ele <=high and count<5:
        students_within_25_and_75.append(d[ele])
        count=count+1
        

    return top_5_students, least_5_students, students_within_25_and_75,d

top_5_students, least_5_students, students_within_25_and_75,dic = display_dash_board(students, marks)
#Getting the marks for a given student from dict
def get_key(val):
  for key,value in dic.items():
    if val == value:
      return key
marks = []
for ele in top_5_students:
  marks.append(get_key(ele))
print('a.')
for i in range(len(top_5_students)):
  print('{0} {1}'.format(top_5_students[i],marks[i]))
marks=[]
for ele in least_5_students:
  marks.append(get_key(ele))
print('b.')
for i in range(len(least_5_students)):
  print('{0} {1}'.format(least_5_students[i],marks[i]))
marks=[]
for ele in students_within_25_and_75:
  marks.append(get_key(ele))
print('c.')
for i in range(len(students_within_25_and_75)):
  print('{0} {1}'.format(students_within_25_and_75[i],marks[i]))


a.
student8 98
student10 80
student2 78
student5 48
student7 47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [5]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


def dist(S,P):
  """Finding the cosine similarity distance 
between the points"""

  (x,y) = S
  (p,q) = P
  num = (x*p)+(y*q)
  den = math.sqrt(x**2+y**2)*math.sqrt(p**2+q**2)
  return math.acos(num/den)

# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    dct = {} #Storing the distance and corresponding Si as key-value pairs
    dis = [] # Storing the distance between Si's and P as list
    for point in S:
      dis.append(dist(point,P))
    i=0
    for length in dis:
      dct[length] = S[i]
      i=i+1
    dis.sort()
    closest_points_to_p = []
    for i in range(5) :
      closest_points_to_p.append(dct[dis[i]])
    return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print("Output :")
for ele in points:
  print(ele) #print the returned values

Output :
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [6]:
import math,functools
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
def extract(line):
  """Extracts the coeffeicents from the line string"""
  line = line.replace('x',',').replace('y',',').split(',')
  no = []
  for ele in line:
    no.append(float(ele))
  return no
def f(a,b,c,x):
  """For a given co-ordinate and x component, computes the y component satisfiying the eqn 
of the line"""
  if (a==0):
    return c
  else:
    return (-b/a)*x+c
def dist(x,y,x1,y1,x2,y2):
  """Tells if the point is on side or the other side based on the sign of the 
return value"""
  return (x-x1)*(y2-y1)-(y-y1)*(x2-x1)
# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    no = extract(line) #Extracted the coeffs and stored in an array for the given line equatiion
    P1=[1,1] # A random point P1(1,y) initialized with x component as 1 and to compute the y component satisfying the given eqn
    P2=[2,1] # A random point P2(2,y) initialized with x component as 2 and to compute the y component satisfying the given eqn
    P2[1] = f(no[0],no[1],no[2],P2[0])
    P1[1] = f(no[0],no[1],no[2],P1[0])
    Red_res=[] # To store dist values for all red points
    Blue_res=[] # To store dist value for all blue points
    for point in Red:
      Red_res.append(dist(point[0],point[1],P1[0],P1[1],P2[0],P2[1]))
    for point in Blue:
      Blue_res.append(dist(point[0],point[1],P1[0],P1[1],P2[0],P2[1]))
    """To test whether all blue and red points are classifed completely
Blue_res and Red_res arrays are mutated to hold only the signs of dist values.
Completed seperable by the lines means blue points will have a single sign and
red points will have the opposite sign.
If the number of signs in blue is additive inverse of number of signs of red return yes """
    for i in range(len(Blue_res)):
      if (Blue_res[i]==0):
        continue
      Blue_res[i]/=abs(Blue_res[i])
    for i in range(len(Red_res)):
      if (Red_res[i]==0):
        continue
      Red_res[i]/=abs(Red_res[i])
  
    sum1 = functools.reduce(lambda a,b : a+b,Blue_res)
    sum2=functools.reduce(lambda a,b : a+b,Red_res)
    if (sum1*-1==sum2):
      return "YES"
    else:
      return "NO"
    return #yes/no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

print('Output :')
for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

Output :
YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [18]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
# Reference: https://stackoverflow.com/questions/57179618/filling-the-missing-values-in-the-specified-format-python

def modify(arr,i,j):
  """Modifiying the empty gaps with values"""
  if i==-1: #If str starts with '_' calculating the average value based on number of '_'
    v= float(arr[j])/(j+1)
    for k in range(i+1,j+1):
      arr[k]=v
  elif j==-1: # If str ends with '_' calculating the average value based on number of '_'
    l=len(arr)-i
    v = float(arr[i])/l
    for k in range(i,len(arr)):
      arr[k]=v
  else:
    v = (float(arr[i])+float(arr[j]))/(j-i+1)
    for k in range(i,j+1):
      arr[k] = v
  return arr

# you can free to change all these codes/structure
def curve_smoothing(string):
  arr=string.split(',')
  index_N=[] #Storing the index of numbers
  for i in range(len(arr)):
    if (arr[i]!='_'):
      index_N.append(i)
  if index_N[0]!=0: #If str starts with '_' unshift array with -1
    index_N = [-1] + index_N
  if index_N[-1]!=len(arr)-1: # If str ends with '_' append -1 to array
    index_N.append(-1)
  for (i,j) in zip(index_N[:-1], index_N[1:]):
        modify(arr,i,j) #Modiying the string 
  for i in range(len(arr)):
    arr[i]=int(arr[i])
  return arr

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [8]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    count_S=[0]*3 #List to store count of Si's with i-1 being the index
    for sub_list in A:
      if sub_list[1]=='S1':
        count_S[0]+=1
      elif sub_list[1]=='S2':
        count_S[1]+=1
      elif sub_list[1]=='S3':
        count_S[2]+=1
      else:
        continue
    # A dct to store the count of Fi's given Si
    #If count of F1 given S1 = 1 that value is stored in list[0] of key S1
    #count of Fi is stored in that index (i-1) of list with key Si
    dct={'S1':[0,0,0,0,0],'S2':[0,0,0,0,0],'S3':[0,0,0,0,0]}
    for sub_list in A:
      if sub_list[0]=='F1':
        dct[sub_list[1]][0]+=1
      if sub_list[0]=='F2':
        dct[sub_list[1]][1]+=1
      if sub_list[0]=='F3':
        dct[sub_list[1]][2]+=1
      if sub_list[0]=='F4':
        dct[sub_list[1]][3]+=1
      if sub_list[0]=='F5':
        dct[sub_list[1]][4]+=1
    print("a. P(F=F1|S==S1)={0}/{1}, P(F=F1|S==S2)={2}/{3}, P(F=F1|S==S3)={4}/{5}".format(dct['S1'][0],count_S[0],dct['S2'][0],count_S[1],dct['S3'][0],count_S[2]))
    print("b. P(F=F2|S==S1)={0}/{1}, P(F=F2|S==S2)={2}/{3}, P(F=F2|S==S3)={4}/{5}".format(dct['S1'][1],count_S[0],dct['S2'][1],count_S[1],dct['S3'][1],count_S[2]))
    print("c. P(F=F3|S==S1)={0}/{1}, P(F=F3|S==S2)={2}/{3}, P(F=F3|S==S3)={4}/{5}".format(dct['S1'][2],count_S[0],dct['S2'][2],count_S[1],dct['S3'][2],count_S[2]))
    print("d. P(F=F4|S==S1)={0}/{1}, P(F=F4|S==S2)={2}/{3}, P(F=F4|S==S3)={4}/{5}".format(dct['S1'][3],count_S[0],dct['S2'][3],count_S[1],dct['S3'][3],count_S[2]))
    print("d. P(F=F5|S==S1)={0}/{1}, P(F=F5|S==S2)={2}/{3}, P(F=F5|S==S3)={4}/{5}".format(dct['S1'][4],count_S[0],dct['S2'][4],count_S[1],dct['S3'][4],count_S[2]))
    
    

    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
compute_conditional_probabilites(A)

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
d. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [9]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
  S1=list(S1.split(' '))
  S2=list(S2.split(' '))
  dct={} # Using a dict to keep track of common words
  res=[] # and storing common words in list
  for word in S1:
    dct[word]=1
  for word in S2:
    if (word in dct):
      res.append(word)
  a=len(res)  
  set1=set(S1)
  set2=set(S2)
  b=list(set1-set2) # this Set difference gives words in S1 but not in S2
  c=list(set2-set1) # this Set difference gives  Words in S2 but not in S1
  return a, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print("a. {0}".format(a))
print("b. {0}".format(b))
print("c. {0}".format(c))


a. 7
b. ['first', 'F', '5']
c. ['3', 'S', 'second']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [10]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math
def f(y,y_score):
  """Defining the loss function for single component 
given a y and y_score values"""
  term1 = y*math.log(y_score,10)
  term2 = (1-y)*math.log(1-y_score,10)
  return term1+term2

# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
  loss=0.0
  for ele in A:
    loss+=f(ele[0],ele[1])
  loss/=-len(A)
  return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print("Output :")
print(loss)

Output :
0.42430993457031635
